### PR TITLE
Fix current npm broken. Remove babel-polyfill import

### PR DESCRIPTION
**Pull request by bySabi**
Hi @dennybritz 

Current npm 0.2.4 is broken. This PR fix that.

I changed `Object.assign` to `jQuery.extend`. Now is more IE9 and mobile compliant without `babel-polyfill` dependencies.

### CODE REVIEW

**Comment by dennybritz** [comment]
I don't understand, why is it broken? I'd really not rely on jQuery.

**Comment by bySabi** [comment]
Cause this line: https://github.com/dennybritz/neal-react/blob/master/js/app.js#L1 it broke if `babel-polyfill` npm is unmet. Adding the whole polyfill only for `Object.assign` IMO is not adecuate.

This package already use jQuery: https://github.com/dennybritz/neal-react/blob/master/js/components/vendor/stripe.jsx#L14. jQuery is needed for `Bootstrap 4` module.

**Comment by bySabi** [comment]
Hi @dennybritz do you already see the problem?

**Comment by dennybritz** [comment]
I decided to keep `babel-polyfill` in. It's true that it's currently not used beyond `Object.assign` but I think it may be useful in the future when adding new features. I moved it back into the dependencies.

I'd love to get rid of the jQuery dependency someday. Not everyone needs the Bootstrap Javascript.

**Pull request closed without merging**
