### PR TITLE
add customizable className to Navbar

### PR DESCRIPTION
**Pull request by bySabi**
Hi @dennybritz this is for make `Navbar` more customizable via `className`

This way anyone can, for example, create navbar fixed at top `navbar-fixed-top`.

sample-page.jsx

```
export default (props) => (
  <Page>
    <Navbar brand={brand} className="navbar-fixed-top">
...
```

This PR don´t broke current `neal-sample`

### CODE REVIEW

**Comment by bySabi** [comment]
Hello again @dennybritz. Can you review this PR.

I move `react` dependency to peerDependencies and add React `>15.0.0-rc` version. Is more convenient for test incoming React release.
`babel-polyfill` is moved too, Bootstrap 4 will not support old browser IE's. This dependency must be optional.

Thanks for your work. :+1:

**Comment by dennybritz** [comment]
Oops, sorry for the late reply, I somehow missed this PR. Looks good.

**Comment by bySabi** [comment]
Not problem @dennybritz :-)

Don´t forget update npm version number.

**Comment by dennybritz** [comment]
Yep, updated it.

**Pull request merged**
